networks:
  dmz_network:
    external: true
    name: opt_dmz_network

services:
  # Сервер мессенджера
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: messenger-server
    ports:
      - "${SERVER_PORT:-9095}:9095"
      - "9091:9091"  # WebSocket порт
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres12345!}@db:5432/${DB_NAME:-messenger}?sslmode=disable
      - JWT_SECRET=${JWT_SECRET:-gp2Ju8PPFTvLA4WRbDDNF5jUQ2sX7KcP}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres12345!}
      - DB_NAME=${DB_NAME:-messenger}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - DEBUG=${DEBUG:-true}
      - SERVER_PORT=${SERVER_PORT:-9095}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-devkey}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-devsecret123}
      - LIVEKIT_URL=${LIVEKIT_URL:-ws://livekit:7880}
      - SSE_KEY_BASE64=${SSE_KEY_BASE64:-M3pjL1YwdURHbVgrQkRFdlhMRDZ1VzhxT1FFUG1WdmV0THRnZU8yYUhMWT0=}
      - SERVER_ENCRYPTION_KEY=${SSE_KEY_BASE64:-M3pjL1YwdURHbVgrQkRFdlhMRDZ1VzhxT1FFUG1WdmV0THRnZU8yYUhMWT0=}
      - REDIS_ENABLED=true
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_JSON=${LOG_JSON:-true}
      - APP_ENV=${APP_ENV:-development}
      - SERVER_HOST=0.0.0.0
      - WEBSOCKET_PORT=9091
      - CONFIG_PATH=/app/config/config.json
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Adm1n$3cureP@ss}
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./logs/server:/app/logs
    networks:
      dmz_network:
        ipv4_address: 10.16.52.15
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Клиентское приложение
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "55581:80"  # Веб-клиент на порту 55581 для прокси
    depends_on:
      - server
    restart: unless-stopped
    networks:
      dmz_network:
        ipv4_address: 10.16.52.16
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # База данных PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: messenger-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres12345!}
      POSTGRES_DB: ${DB_NAME:-messenger}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      dmz_network:
        ipv4_address: 10.16.52.17
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis для WebSocket масштабирования
  redis:
    image: redis:7-alpine
    container_name: messenger-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      dmz_network:
        ipv4_address: 10.16.52.18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pg_data:
  redis_data:
